name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Initial setup
        run: |
          go mod init

      - name: Build Release
        run: |
          make -j$(($(nproc) + 1)) releases

      - name: Delete tag Stable if exists
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: Stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Prerelease
        uses: richardsimko/update-tag@v1
        with:
          tag_name: Stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: Stable
          files: bin/*
          draft: false
          generate_release_notes: true
